#!/usr/bin/env bash
# Transfers a file from our clint to a server; accepts 4 parameters
# Before running this script, you can run this to list the server's exiting contents
# After running script, we will run this to check new content is transfered

if [ "$#" -lt 4 ]; then
       echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2:~/
fi
