#!/usr/bin/env bash
# nstall nginx and print HS when starts
apt-get update
apt-get -y install nginx
service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
