#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure nginx to listen to post 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx reloadi

# Create a simple HTML file with "Hello World!"
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
