#!/usr/bin/env bash
# A bash script to print best schoo; 10x but for the 9th iteratiion print hi

i=1
while [ "$i" -le 10 ]
do
     echo "Best School"
     if [ "$i" -eq 9 ]
     then
          echo "Hi"
     fi
     (( i++))
done
