#!/usr/bin/env bash
# print num 1-20 but bad luck at 4th, bad luck at 6th, bad luck at 17

i=1
while [ "$i" -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( i++ ))
done
